# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'SCC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SCC

pod 'YYModel', '1.0.4'
pod 'SDWebImage', '3.8.2'
pod 'AFNetworking', '3.1.0'
pod 'YYText', '1.0.7'
pod 'Masonry'
pod 'MJRefresh', '3.1.12'
pod 'SVProgressHUD', '1.1.3'
pod 'WechatOpenSDK'
pod 'UMCCommon'
pod 'UMCAnalytics'
pod 'UMCSecurityPlugins'
# 集成微信(精简版0.2M)
pod ‘UMengUShare/Social/ReducedWeChat'

# 集成QQ(精简版0.5M)
pod ‘UMengUShare/Social/ReducedQQ'
end
